product-name: gcp-service-broker
network-properties:
  network:
    name: ((network_name))
  other_availability_zones:
  - name: ((singleton_availability_zone))
  singleton_availability_zone:
    name: ((singleton_availability_zone))
product-properties:
  .properties.db_host:
    value: ((db_host))
  .properties.db_name:
    value: ((db_name))
  .properties.db_port:
    value: ((db_port))
  .properties.gcp_service_broker_enable_global_access_to_plans:
    value: ((gcp_service_broker_enable_global_access_to_plans))
  .properties.gsb_brokerpak_config:
    value: ((gsb_brokerpak_config))
  .properties.gsb_compatibility_enable_builtin_services:
    value: ((gsb_compatibility_enable_builtin_services))
  .properties.gsb_compatibility_enable_catalog_schemas:
    value: ((gsb_compatibility_enable_catalog_schemas))
  .properties.gsb_compatibility_enable_cf_sharing:
    value: ((gsb_compatibility_enable_cf_sharing))
  .properties.gsb_compatibility_enable_eol_services:
    value: ((gsb_compatibility_enable_eol_services))
  .properties.gsb_compatibility_enable_gcp_beta_services:
    value: ((gsb_compatibility_enable_gcp_beta_services))
  .properties.gsb_compatibility_enable_gcp_deprecated_services:
    value: ((gsb_compatibility_enable_gcp_deprecated_services))
  .properties.gsb_compatibility_enable_preview_services:
    value: ((gsb_compatibility_enable_preview_services))
  .properties.gsb_compatibility_enable_terraform_services:
    value: ((gsb_compatibility_enable_terraform_services))
  .properties.gsb_compatibility_enable_unmaintained_services:
    value: ((gsb_compatibility_enable_unmaintained_services))
  .properties.gsb_service_google_bigquery_bind_defaults:
    value: ((gsb_service_google_bigquery_bind_defaults))
  .properties.gsb_service_google_bigquery_provision_defaults:
    value: ((gsb_service_google_bigquery_provision_defaults))
  .properties.gsb_service_google_bigtable_bind_defaults:
    value: ((gsb_service_google_bigtable_bind_defaults))
  .properties.gsb_service_google_bigtable_provision_defaults:
    value: ((gsb_service_google_bigtable_provision_defaults))
  .properties.gsb_service_google_cloudsql_mysql_bind_defaults:
    value: ((gsb_service_google_cloudsql_mysql_bind_defaults))
  .properties.gsb_service_google_cloudsql_mysql_provision_defaults:
    value: ((gsb_service_google_cloudsql_mysql_provision_defaults))
  .properties.gsb_service_google_cloudsql_postgres_bind_defaults:
    value: ((gsb_service_google_cloudsql_postgres_bind_defaults))
  .properties.gsb_service_google_cloudsql_postgres_provision_defaults:
    value: ((gsb_service_google_cloudsql_postgres_provision_defaults))
  .properties.gsb_service_google_ml_apis_bind_defaults:
    value: ((gsb_service_google_ml_apis_bind_defaults))
  .properties.gsb_service_google_ml_apis_provision_defaults:
    value: ((gsb_service_google_ml_apis_provision_defaults))
  .properties.gsb_service_google_pubsub_bind_defaults:
    value: ((gsb_service_google_pubsub_bind_defaults))
  .properties.gsb_service_google_pubsub_provision_defaults:
    value: ((gsb_service_google_pubsub_provision_defaults))
  .properties.gsb_service_google_spanner_bind_defaults:
    value: ((gsb_service_google_spanner_bind_defaults))
  .properties.gsb_service_google_spanner_provision_defaults:
    value: ((gsb_service_google_spanner_provision_defaults))
  .properties.gsb_service_google_storage_bind_defaults:
    value: ((gsb_service_google_storage_bind_defaults))
  .properties.gsb_service_google_storage_provision_defaults:
    value: ((gsb_service_google_storage_provision_defaults))
  .properties.root_service_account_json:
    value: ((root_service_account_json))
resource-config:
  delete-all:
    instance_type:
      id: ((delete-all_instance_type))
  deploy-all:
    instance_type:
      id: ((deploy-all_instance_type))
errand-config:
  delete-all:
    post-deploy-state: ((delete-all_post_deploy_state))
    pre-delete-state: ((delete-all_pre_delete_state))
  deploy-all:
    post-deploy-state: ((deploy-all_post_deploy_state))
    pre-delete-state: ((deploy-all_pre_delete_state))
